//
// Created by udara on 6/16/23.
//

#pragma once

#define RESULT_SUCCESS 0
#define ERROR_NULL_ENCODER 1
#define ERROR_INVALID_ENCODER_INSTANCE 2
#define ERROR_VERSION_MISMATCH 3
#define ERROR_FAILED_TO_GET_BITMAP_INFO 4
#define ERROR_INVALID_BITMAP_FORMAT 5
#define ERROR_RESIZE_BITMAP_FAILED 6
#define ERROR_LOCK_BITMAP_PIXELS_FAILED 7
#define ERROR_UNLOCK_BITMAP_PIXELS_FAILED 8
#define ERROR_MEMORY_ERROR 9
#define ERROR_ADD_FRAME_FAILED 10
#define ERROR_MARK_ANIMATION_END_FAILED 11
#define ERROR_ANIMATION_ASSEMBLE_FAILED 12
#define ERROR_INVALID_WEBP_CONFIG 13
#define ERROR_BITMAP_URI_DECODE_FAILED 14
#define ERROR_WRITE_TO_URI_FAILED 15
#define ERROR_WEBP_ENCODE_FAILED 16

std::string parseErrorMessage(int error_code);