name: Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
  SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}

jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17

      - name: Check out webp-android
        uses: actions/checkout@v3
        with:
          ref: v1.1.1
          path: webp-android

      - name: Check out libwebp
        uses: actions/checkout@v3
        with:
          repository: webmproject/libwebp
          ref: 1.5.0
          path: libwebp

      - name: Release build webp-android
        working-directory: webp-android
        run: ./gradlew :webp-android:assembleRelease

      - name: Publish webp-android to MavenCentral
        working-directory: webp-android
        run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
