name: Publish

on:
  release:
    # We'll run this workflow when a new GitHub release is created
    types: [released]
  workflow_dispatch:

jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out version-catalog
        uses: actions/checkout@v3
        with:
          repository: UdaraWanasinghe/android-version-catalog
          path: version-catalog
          fetch-depth: 1

      - name: Check out webp-android
        uses: actions/checkout@v3
        with:
          path: webp-android

      - name: Check out libwebp
        uses: actions/checkout@v3
        with:
          repository: webmproject/libwebp
          ref: v1.3.0
          path: libwebp
          fetch-depth: 1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17

        # Build and publish version catalog
      - name: Publish version-catalog
        working-directory: version-catalog
        run: ./gradlew publishToMavenLocal

        # Builds the release artifacts of the library
      - name: Release build
        working-directory: webp-android
        run: ./gradlew :webp-android:assembleRelease

        # Generates source artifacts
      - name: Source jar
        working-directory: webp-android
        run: ./gradlew androidSourcesJar

        # Runs upload, and then closes & releases the repository
      - name: Publish to MavenCentral
        working-directory: webp-android
        run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}