name: Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17

      - name: Check out version-catalog
        uses: actions/checkout@v3
        with:
          repository: UdaraWanasinghe/android-version-catalog
          token: ${{ secrets.VERSION_CATALOG_ACCESS_TOKEN }}
          path: version-catalog

      - name: Check out webp-android
        uses: actions/checkout@v3
        with:
          path: webp-android

      - name: Check out libwebp
        uses: actions/checkout@v3
        with:
          repository: webmproject/libwebp
          ref: v1.3.0
          path: libwebp

      - name: Publish version-catalog
        working-directory: version-catalog
        run: ./gradlew publishToMavenLocal

      - name: Release build webp-android
        working-directory: webp-android
        run: ./gradlew :webp-android:assembleRelease

      - name: Publish webp-android to MavenCentral
        working-directory: webp-android
        run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}