-keep class com.aureusapps.android.webpandroid.utils.BitmapUtils {*;}
-keep class com.aureusapps.android.webpandroid.extensions.UriExtensionsKt {*;}
-keep class com.aureusapps.android.webpandroid.decoder.**
-keep class com.aureusapps.android.webpandroid.decoder.** {*;}
-keep class com.aureusapps.android.webpandroid.encoder.**
-keep class com.aureusapps.android.webpandroid.encoder.** {*;}