-keep class com.aureusapps.android.extensions.BitmapUtils {*;}
-keep class com.aureusapps.android.extensions.UriExtensionsKt {*;}
-keep class com.aureusapps.android.webpandroid.decoder.**
-keep class com.aureusapps.android.webpandroid.decoder.** {*;}
-keep class com.aureusapps.android.webpandroid.encoder.**
-keep class com.aureusapps.android.webpandroid.encoder.** {*;}